version: "3"

services:
  gql-app:
    container_name: gql-app-container
    build: 
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/src
    env_file:
      - .env.dev
    depends_on:
      - gql-db

  gql-db:
    image: postgres:14-alpine
    container_name: gql-db
    ports:
      - 5555:5432
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_DB: gql-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"