// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Item struct {
	ID    int    `gorm:"primaryKey;autoIncrement"`
	Text  string `json:"text"`
	Price int    `json:"price"`
}

type ItemConnection struct {
	Items    []*Item   `json:"items"`
	PageInfo *PageInfo `json:"pageInfo"`
}

type NewItem struct {
	Name   string `json:"name"`
	Price  int    `json:"price"`
	UserID string `json:"userId"`
}

type NewUser struct {
	Name string `json:"name"`
}

type PageInfo struct {
	StartCursor int `json:"startCursor"`
	EndCursor   int `json:"endCursor"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
